name: master0
version: "3"
services:
    bind9:
        container_name: bind9
        image: ubuntu/bind9:latest
        environment:
        - BIND9_USER=root
        - TZ=Europe/Paris
        ports:
        - "53:53/tcp"
        - "53:53/udp"
        volumes:
        - /etc/bind:/etc/bind
        - /var/cache/bind:/var/cache/bind
        - /var/lib/bind:/var/lib/bind
        restart: unless-stopped
    radius:
        container_name: radius
        image: freeradius/freeradius-server:latest
        ports:
        - "1812:1812/udp"
        - "1813:1813/udp"
        build:
            dockerfile_inline: |
                FROM freeradius/freeradius-server:latest
                COPY raddb/ /etc/raddb/
        command: -X
        restart: unless-stopped