name: master0
version: "3"
services:
    bind9:
        container_name: bind9
        image: ubuntu/bind9:latest
        environment:
        - BIND9_USER=root
        - TZ=Europe/Paris
        ports:
        - "53:53/tcp"
        - "53:53/udp"
        volumes:
        - /var/cache/bind:/var/cache/bind
        - /var/lib/bind:/var/lib/bind
        build:
            context: /
            dockerfile_inline: |
                FROM ubuntu/bind9:latest
                COPY /etc/bind/ /etc/bind/
        restart: unless-stopped