# Network configuration for router3.
network:
  version: 2
  ethernets:
    # Interfaz para la red de la organización externa.
    eth-servidores-dorayaki:
      match:
        macaddress: 08:00:27:00:99:00
      dhcp4: no
      dhcp6: no
      addresses:
        - 172.16.2.254/24
      set-name: eth0
      routes:
        - to: default
          via: 172.16.2.1