# Network configuration for router3.
network:
  # Uso del DNS de Dorayaki por defecto. En este caso la propia máquina.
  nameservers:
    addresses: [127.0.0.1, 8.8.8.8]
  version: 2
  ethernets:
    # Interfaz para la red de la organización externa.
    eth-servidores-dorayaki:
      match:
        macaddress: 08:00:27:00:99:00
      dhcp4: yes
      dhcp6: no
      addresses:
        - 172.16.1.254/24
      set-name: eth0
      routes:
        - to: default
          via: 172.16.2.1