# From: https://github.com/ethnchao/docker-nagios/blob/master/docker-compose.yml

version: '2'
services:
  nagios:
    image: ethnchao/nagios
    container_name: nagios
    command: --enable-ndo --create-db --server-url http://auditoria.dorayaki.org:4000
    ports:
      - 4000:80
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - nagios_mysql
    volumes:
      - /data/nagios/plugin:/data/plugin
      - /data/nagios/conf:/usr/local/nagios/etc/mount
      - /data/nagios/example:/data/example

  nagios_mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 13306:3306
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - MYSQL_USER=nagios
      - MYSQL_PASSWORD=nagios
      - MYSQL_ADDRESS=nagios_mysql
      - MYSQL_DATABASE=nagios
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - nagios_db_data:/var/lib/mysql

volumes:
  nagios_db_data:
