# Network configuration for router2.
network:
  version: 2
  ethernets:
    # Interfaz para la salida a internet.
    eth-internet:
      match:
        macaddress: 08:00:27:00:01:00
      dhcp4: yes
      # Ignorar DNS anunciados por DHCP en la interfaz NAT.
      dhcp4-overrides:
        use-dns: no
      set-name: eth0
    # Interfaz para la red del ISP con Dorayaki.
    eth-isp-dorayaki:
      match:
        macaddress: 08:00:27:00:01:01
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.2.3.1/30
      set-name: eth1
      # Tabla de rutas hacia la sede Dorayaki.
      routes:
        # Ruta para la red de la oficina de Dorayaki
        - to: 172.16.1.0/24
          via: 10.2.3.2
        # Ruta para la red de servidores de Dorayaki
        - to: 172.16.2.0/24
          via: 10.2.3.2
      # Uso del DNS de Dorayaki por defecto.
      nameservers:
        addresses: [172.16.2.254]
    # Interfaz para le red del ISP con la organización externa.
    eth-isp-ognarizacion-externa:
      match:
          macaddress: 08:00:27:00:01:02
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.2.3.5/30
      set-name: eth2
      # Tabla de rutas hacia la organización externa
      routes:
        - to: 192.168.1.0/24
          via: 10.2.3.6
    # Interfaz para la red del ISP con el host de auditoría.
    eth-isp-auditoria:
      match:
          macaddress: 08:00:27:00:01:03
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.2.3.65/26
      set-name: eth3