# Network configuration for router3.
network:
  version: 2
  ethernets:
    # Interfaz para la red de la organización externa.
    eth-orgnaizacion-externa:
      match:
        macaddress: 08:00:27:00:02:00
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.1/24
      set-name: eth0
    # Interfaz para le red del ISP con la organización externa.
    eth-isp-ognarizacion-externa:
      match:
          macaddress: 08:00:27:00:02:01
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.2.3.6/30
      set-name: eth1
      # Tabla de rutas por defecto.
      routes:
        - to: default
          via: 10.2.3.5
      # Uso del DNS de Dorayaki por defecto.
      nameservers:
        addresses: [172.16.2.254]