services:
  snort:
    image: linton/docker-snort
    network_mode: host
    stdin_open: true
    command: /bin/bash
    tty: true
    container_name: snort
    volumes:
      - /etc/snort/rules:/etc/snort/rules