# Network configuration for router-isp.
network:
  version: 2
  ethernets:
    # Interfaz para la salida a internet.
    eth-internet:
       match:
        macaddress: 08:00:27:00:01:00
      dhcp4: yes
      set-name: eth0
    # Interfaz para la red del ISP con Dorayaki.
    eth-isp-dorayaki:
      match:
        macaddress: 08:00:27:00:01:01
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.16.0.254/24
      set-name: eth1
      # Tabla de rutas hacia la sede Dorayaki.
      routes:
        # Ruta para la red de la oficina de Dorayaki
        - to: 10.0.0.0/16
          via: 10.16.0.1
        # Ruta para la red de servidores de Dorayaki
        - to: 10.1.0.0/16
          via: 10.16.0.1
    # Interfaz para le red del ISP con la organización externa.
    eth-isp-ognarizacion-externa:
      match:
          macaddress: 08:00:27:00:01:02
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.16.1.254/24
      set-name: eth2
      # Tabla de rutas hacia la organización externa
      routes:
        - to: 10.8.0.0/16
          via: 10.16.1.1
    # Interfaz para la red del ISP con el host de auditoría.
    eth-isp-auditoria:
      match:
          macaddress: 08:00:27:00:01:03
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.16.2.254/24
      set-name: eth3