version: '3'

name: squid
services:
    squid:
        container_name: squid
        environment:
            - TZ=UTC
        volumes:
            - /etc/path/to/data:/var/spool/squid
            - /etc/path/to/main/config:/etc/squid/
        ports:
            - 3128:3128
        image: ubuntu/squid:5.2-22.04_beta

